<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMaster.master" AutoEventWireup="true" CodeFile="ZipCodeManagement.aspx.cs" Inherits="Administration_ZipCodeManagement" %>

<asp:Content ID="Content1" ContentPlaceHolderID="Content" Runat="Server">
    <h2>Zip Codes Management</h2>
<asp:DropDownList runat="server" ID="ddlFed" CssClass="fed-ddl" AutoPostBack="True" DataSourceID="odsFed" DataValueField="ID" DataTextField="Name" AppendDataBoundItems="True" OnSelectedIndexChanged="ddlFed_SelectedIndexChanged">
    <asp:ListItem Value="0" Text="Please select a program"></asp:ListItem>
</asp:DropDownList>
<asp:ObjectDataSource ID="odsFed" runat="server" TypeName="FederationsDA" SelectMethod="GetAllActiveFederations">
    <SelectParameters>
        <asp:SessionParameter SessionField="RoleID" Name="UserRole" Type="Int32" />
        <asp:SessionParameter SessionField="FedID" Name="FedID" Type="Int32" />
    </SelectParameters>     
</asp:ObjectDataSource>
    
<asp:Panel runat="server" ID="pnlAddNew" Visible="False" style="margin:20px">
    <asp:TextBox runat="server" ID="txtNewZipCode"></asp:TextBox>&nbsp;
    <asp:Button runat="server" ID="btnAdd" Text="Add New Zip Code" OnClick="btnAdd_Click"/>    
    <br/>
    <asp:Label runat="server" ID="lblMsg" ForeColor="Red"></asp:Label>
</asp:Panel>


<asp:GridView runat="server" ID="gv" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" DataKeyNames="ID" style="margin:20px"
    BorderWidth="1px"  
             CellPadding="3" CellSpacing="2" BorderStyle="None" 
             AlternatingRowStyle-BackColor="lightgray"
    >
    <Columns>
        <asp:BoundField ReadOnly="True" Visible="false" HeaderText="ID" DataField="ID">
            <ItemStyle HorizontalAlign="Center"></ItemStyle>
        </asp:BoundField>
        <asp:BoundField HeaderText="Zip Code" DataField="ZipCode">
            <ItemStyle HorizontalAlign="Center"></ItemStyle>
        </asp:BoundField>
    </Columns>
</asp:GridView>    
    
<asp:ObjectDataSource ID="odsZipCodes" runat="server" TypeName="ZipCodeDA" SelectMethod="GetZipCodes" deletemethod="DeleteZipCode">
    <SelectParameters>
        <asp:ControlParameter ControlID="ddlFed" PropertyName="SelectedValue" Name="fedId" Type="Int32" />
    </SelectParameters>    
    <DeleteParameters>
        <asp:parameter name="ID" type="Int32" />
    </DeleteParameters> 
</asp:ObjectDataSource>
</asp:Content>

